CREATE TABLE `FRM_FORMULARIOS` (
`FORM_ID` int NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(1000) NOT NULL,
`DESCRIPCION` varchar(3000) NULL,
`HABILITADO` boolean NOT NULL DEFAULT true,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`FEC_DEPRECACION` timestamp NULL,
`USUARIO` varchar(100) NULL,
PRIMARY KEY (`FORM_ID`) 
);

CREATE TABLE `FRM_CATEGORIAS` (
`CATE_ID` int NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(1000) NOT NULL,
`ORDEN` int NOT NULL,
`PISTA` varchar(2000) NULL,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`FORM_ID` int NOT NULL,
PRIMARY KEY (`CATE_ID`) 
);

CREATE TABLE `FRM_GRUPOS` (
`GRUP_ID` int NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(1000) NOT NULL,
`ORDEN` int NOT NULL,
`PISTA` varchar(1000) NULL,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`CATE_ID` int NULL,
PRIMARY KEY (`GRUP_ID`) 
);

CREATE TABLE `FRM_VALORES` (
`VALO_ID` int NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(2000) NOT NULL,
`ORDEN` int NOT NULL,
`PISTA` varchar(2000) NULL,
`LONGITUD` int NULL,
`VALOR_DEFECTO` varchar(1000) NULL,
`OBLIGATORIO` boolean NOT NULL,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`TIDA_ID` int NOT NULL,
`GRUP_ID` int NOT NULL,
PRIMARY KEY (`VALO_ID`) 
);

CREATE TABLE `FRM_VALORES_POSIBLES` (
`VAPO_ID` int NOT NULL AUTO_INCREMENT,
`VALOR` varchar(100) NOT NULL,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`VALO_ID` int NOT NULL,
PRIMARY KEY (`VAPO_ID`) 
);

CREATE TABLE `FRM_TIPOS_DATO` (
`TIDA_ID` int NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(100) NOT NULL,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`TIDA_ID`) 
);

CREATE TABLE `FRM_FORMULARIOS_COMPLETADOS` (
`FOCO_ID` int NOT NULL AUTO_INCREMENT,
`FORM_NOMBRE` varchar(1000) NOT NULL,
`CATE_NOMBRE` varchar(1000) NOT NULL,
`GRUP_NOMBRE` varchar(1000) NOT NULL,
`VALO_NOMBRE` varchar(2000) NOT NULL,
`TIDA_NOMBRE` varchar(100) NOT NULL,
`ORDEN` int NOT NULL,
`VALOR` longtext NOT NULL,
`FORM_ID` int NOT NULL,
`REFERENCIA` text NULL,
`FEC_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`USUARIO` varchar(100) NOT NULL,
PRIMARY KEY (`FOCO_ID`) 
);


ALTER TABLE `FRM_VALORES` ADD CONSTRAINT `fk_FRM_VALORES_FRM_TIPO_DATO_1` FOREIGN KEY (`TIDA_ID`) REFERENCES `FRM_TIPOS_DATO` (`TIDA_ID`);
ALTER TABLE `FRM_CATEGORIAS` ADD CONSTRAINT `fk_FRM_CATEGORIAS_FRM_FORMULARIOS_1` FOREIGN KEY (`FORM_ID`) REFERENCES `FRM_FORMULARIOS` (`FORM_ID`);
ALTER TABLE `FRM_GRUPOS` ADD CONSTRAINT `fk_FRM_GRUPO_FRM_CATEGORIAS_1` FOREIGN KEY (`CATE_ID`) REFERENCES `FRM_CATEGORIAS` (`CATE_ID`);
ALTER TABLE `FRM_VALORES` ADD CONSTRAINT `fk_FRM_VALORES_FRM_GRUPO_1` FOREIGN KEY (`GRUP_ID`) REFERENCES `FRM_GRUPOS` (`GRUP_ID`);
ALTER TABLE `FRM_VALORES_POSIBLES` ADD CONSTRAINT `fk_FRM_VALORES_VALIDOS_FRM_VALORES_1` FOREIGN KEY (`VALO_ID`) REFERENCES `FRM_VALORES` (`VALO_ID`);
ALTER TABLE `FRM_FORMULARIOS_COMPLETADOS` ADD CONSTRAINT `fk_FRM_FORMULARIOS_COMPLETADOS_FRM_FORMULARIOS_1` FOREIGN KEY (`FORM_ID`) REFERENCES `FRM_FORMULARIOS` (`FORM_ID`);

